version: "3"
services:
  code-camp-nginx:
    ports:
      - "9012:80"
  code-camp-backend:
    build:
      context: .
      args:
        NODE_ENV: dev
    environment:
      - NODE_ENV=dev
      - MONGO_USER=grini
      - MONGO_PASSWORD=grini
      - REDIS_SECRET=secret
    volumes:
      - ./:/camp
      - /app/node_modules
    command: npm run dev
