version: "3"
services:
  code-camp-nginx:
    ports:
      - "80:80"
  code-camp-mongo:
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=grini
      - MONGO_INITDB_ROOT_USERNAME=grini
      - MONGO_INITDB_DATABASE=mydatabase
  code-camp-backend:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        NODE_ENV: prod
    environment:
      - NODE_ENV=dev
      - MONGO_USER=grini
      - MONGO_PASSWORD=grini
      - REDIS_SECRET=secret
    command: npm start
